version: '3'

services:
  jupyterhub:
    build: 
      context: ./jupyterhub/jhub_docker_spawner/context
      dockerfile: ../dockerfiles/Dockerfile
    image: jhub_ds:latest #wanglabneuro/jhub_ds:latest
    container_name: jhub_ds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - hub_data:/srv/jupyterhub
      - /etc/ssl/:/etc/ssl/
    environment:
      - DOCKER_JUPYTER_CONTAINER=jlab_matlab:v1
      - DOCKER_NETWORK_NAME=jupyterhub_jupyter
      - HUB_IP=jupyterhub_hub #'0.0.0.0'
      - HOST
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      default:
      jupyter:
        aliases:
          - jupyterhub_hub
  jupyterlab:
    build: 
      context: ./jupyterlab/jlab_matlab/context
      dockerfile: ../dockerfiles/Dockerfile
    image: jlab_matlab:v1 #wanglabneuro/jlab_matlab:v1
    container_name: jupyterlab-throwaway
    volumes:       
      - ~/data/d:/data
      - ~/data/shared_files:/srv/shared_files
      - ~/data/shared_code:/srv/shared_code
    network_mode: none
    command: echo

volumes:
  hub_data:
  
networks:
  jupyter:
    internal: true