version: '3'

services:
  jupyterhub:
    build: 
      context: ./jupyterhub/jhub_docker_spawner/context
      dockerfile: ../dockerfiles/Dockerfile
    image: wanglabneuro/jhub_ds:latest
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub # don't mount a host directory there, the db is there.      
      - /srv/jupyterhub:/home
    environment:
      - DOCKER_JUPYTER_CONTAINER=wanglabneuro/jlab_base:multilanguage
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
    restart: on-failure


  jupyterlab_multi:
    build: 
      context: ./jupyterlab/jlab_multi/context
      dockerfile: ../dockerfiles/Dockerfile
    image: wanglabneuro/jlab_base:multilanguage
    container_name: jupyterlab-multi
    labels:
      - "traefik.enable=false"
    command: echo

  jupyterlab_matlab:
    build: 
      context: ./jupyterlab/jlab_matlab/context
      dockerfile: ../dockerfiles/Dockerfile
    image: wanglabneuro/jlab_matlab:2021b
    container_name: jupyterlab-matlab
    labels:
      - "traefik.enable=false"
    command: echo

  jupyterlab_dlc:
    build: 
      context: ./jupyterlab/jlab_dlc/context
      dockerfile: ../dockerfiles/Dockerfile
    image: wanglabneuro/jlab_dlc:latest
    container_name: jupyterlab-dlc
    labels:
      - "traefik.enable=false"
    command: echo

  jupyterlab_caiman:
    build: 
      context: ./jupyterlab/jlab_caiman/
      dockerfile: ./dockerfiles/Dockerfile
    image: wanglabneuro/jlab_caiman:latest
    container_name: jupyterlab-caiman
    labels:
      - "traefik.enable=false"
    command: echo

  jupyterlab_tensorflow:
    build: 
      context: ./jupyterlab/jlab_tf/
      dockerfile: ./dockerfiles/Dockerfile
    image: wanglabneuro/jlab_tf:latest
    container_name: jupyterlab-tensorflow
    labels:
      - "traefik.enable=false"
    command: echo

  # jupyterlab:
  #   build: 
  #     context: ./jupyterlab/jlab_multi/context
  #     dockerfile: ../dockerfiles/Dockerfile
  #   image: wanglabneuro/jlab_base:multilanguage
  #   container_name: jupyterlab-throwaway
  #   network_mode: none
  #   command: echo

  reverse-proxy:
    image: traefik:1.7
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - ./secret:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  jupyterhub_data: