name: Publish Docker image

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'
  workflow_dispatch:
#     tags: $RELEASE_VERSION # doesn't work with manual trigger 
#  use ${{ steps.meta.outputs.tags }} for build-push-action `tags` field

env:
  REGISTRY: docker.io
  IMAGE_NAME: jhub_ds
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: wanglabneuro/${{ env.IMAGE_NAME }}
      
      # Use current release tag to tag the image
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          
      # Build and push JupyterHub Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          context: ./jupyterhub/jhub_docker_spawner/context
          file: ./jupyterhub/jhub_docker_spawner/dockerfiles/Dockerfile
          push: true
          tags: $RELEASE_VERSION
          labels: ${{ steps.meta.outputs.labels }}
